UploaderExamensApunts/urls.py
# Copyright (C) 2019 Aniol Marti
# This file is part of DAT - UploaderExamensApunts.
#
# DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
#
"""UploaderExamensApunts URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploader.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

uploader/urls.py
# Copyright (C) 2019 Aniol Marti
# This file is part of DAT - UploaderExamensApunts.
#
# DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
#
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('signup',  views.signup, name='signup'),
    path('signup/', views.perform_signup, name='perform_signup'),
]

uploader/models.py
# Copyright (C) 2019 Aniol Marti
# This file is part of DAT - UploaderExamensApunts.
#
# DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
#
from django.db import models
from django.utils import timezone
from .utils.format_checker import ContentTypeRestrictedFileField
from .utils.change_name import change_name
from UploaderExamensApunts.constants import *
import datetime

class Person(models.Model):
    # Django autocompletes plural nouns and writes "Persons" instead of "People".
    class Meta:
        verbose_name_plural = "people"
    MAX_LENGTH = 100

    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH)
    email = models.EmailField(max_length=MAX_LENGTH, unique=True)
    dni = models.CharField(max_length=MAX_LENGTH, unique=True, verbose_name="DNI/NIE")
    punts_capsa = models.PositiveIntegerField(default=0)

class Degree(models.Model):
    MAX_LENGTH = 200
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH)
    nom_curt = models.CharField(max_length=MAX_LENGTH, unique=True)
    ruta = models.CharField(max_length=MAX_LENGTH)

    def __str__(self):
        return self.nom

class Subject(models.Model):
    MAX_LENGTH = 200
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH)
    grau = models.ForeignKey(Degree, on_delete=models.CASCADE)
    ruta = models.CharField(max_length=MAX_LENGTH,
                            help_text="Ruta de l'assignatura (sense incloure el grau).",
                            default="")

    def __str__(self):
        return self.nom

class ExamWeight(models.Model):
    MAX_LENGTH = 200
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH)

    def __str__(self):
        return self.nom

class ExamType(models.Model):
    MAX_LENGTH = 200
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH)

    def __str__(self):
        return self.nom

class DocumentType(models.Model):
    MAX_LENGTH = 200
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=MAX_LENGTH, unique=True)

    def __str__(self):
        return self.nom

class Upload(models.Model):
    from .utils.queries import list_subjects # Import here to avoid circular importing with Person.
    MAX_LENGTH = 250
    EMPTY = [
        ("", "---")
    ]
    YEARS = [
        (str(x) + "_" + str((x+1)%100), str(x) + "-" + str(x + 1)) for x in range(FIRST_YEAR, datetime.datetime.now().year if (
                datetime.datetime.now().month < 9) else datetime.datetime.now().year + 1)
    ]
    SEMESTER = [
        ("primavera", "Primavera"),
        ("tardor", "Tardor"),
    ]

    id = models.AutoField(primary_key=True)
    upload_date = models.DateField(default=timezone.now)
    grau = models.ForeignKey(Degree, on_delete=models.CASCADE)
    assignatura = models.ForeignKey(Subject, on_delete=models.CASCADE)
    professor = models.CharField(max_length=MAX_LENGTH, blank=True, default="")
    dni = models.CharField(max_length=MAX_LENGTH)
    alumne = models.CharField(max_length=MAX_LENGTH, blank=True, default="")
    curs = models.CharField(max_length=MAX_LENGTH, choices=EMPTY+YEARS)
    quadrimestre = models.CharField(max_length=MAX_LENGTH, choices=EMPTY+SEMESTER)
    document = models.ForeignKey(DocumentType, on_delete=models.CASCADE)
    parcial_final = models.ForeignKey(ExamWeight, on_delete=models.CASCADE, null=True, blank=True)
    tipus_examen = models.ForeignKey(ExamType, on_delete=models.CASCADE, null=True, blank=True)
    solucio = models.BooleanField(default=False)
    file_upload = ContentTypeRestrictedFileField(max_length=MAX_LENGTH, upload_to=change_name, content_types=CONTENT_TYPES, max_upload_size=MAX_FILE_SIZE, null=True, blank=True)
    is_correct = models.BooleanField(default=False)

uploader/forms.py
# Copyright (C) 2019 Aniol Marti
# This file is part of DAT - UploaderExamensApunts.
#
# DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
#
from django import forms
from .models import Upload, Person
from captcha.fields import CaptchaField
from UploaderExamensApunts.constants import *
from .utils.queries import get_degrees

class UploadForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Upload
        fields = ["grau", "assignatura", "professor", "dni", "curs", "quadrimestre", "document", "parcial_final",
                  "tipus_examen", "solucio", "file_upload", "captcha", "alumne"]


class SignUpForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Person
        fields = ["nom", "email", "dni", "captcha"]

uploader/views.py
# Copyright (C) 2019 Aniol Marti
# This file is part of DAT - UploaderExamensApunts.
#
# DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
#
from django.shortcuts import render
from uploader.forms import UploadForm, SignUpForm
from UploaderExamensApunts.constants import *
from .utils.queries import check_dni, get_name, list_subjects, get_degrees, get_document_type_id

def index(request):
    form = UploadForm()
    degrees = get_degrees()
    subjects = {}
    for d in degrees:
        subjects[d.id] = list_subjects(d)
    return render(request, 'uploader/form.html', {'form': form, 'MAX_FILE_SIZE': MAX_FILE_SIZE//1024//1024,
                                                  "content_types": [i.split('/')[1] for i in CONTENT_TYPES if '/' in i],
                                                  "degrees": degrees,
                                                  "subjects": subjects,
                                                  "exam_id": get_document_type_id("Examen")
                                                  })

def upload(request):
    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            if not check_dni(form.cleaned_data["dni"]):
                return render(request, 'uploader/error.html', {'error': "El DNI/NIE introduït no està registrat.",
                                                               "error_info": form.errors})
            upload = form.save(commit=False) # Save the form but don't send it to the DB.
            upload.alumne = get_name(upload.dni)
            upload.save() # Now send it to the DB.
            return render(request, 'uploader/success.html') # Say thank you to the uploader.
        else:
            return render(request, 'uploader/error.html', {'error': "Les dades introduïdes no són vàlides.",
                                                           "error_info": form.errors})
    else:
        return render(request, 'uploader/error.html', {'error': "No s'han introduït dades.",
                                                       "error_info": ""})

def signup(request):
    form = SignUpForm()
    return render(request, 'signup/form.html', {'form': form})

def perform_signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save() # Save the form to the database.
            return render(request, 'signup/success.html') # Say thank you to the uploader.
        else:
            return render(request, 'signup/error.html', {'error': "Les dades introduïdes no són vàlides.",
                                                           "error_info": form.errors})
    else:
        return render(request, 'signup/error.html', {'error': "No s'han introduït dades.",
                                                       "error_info": ""})

uploader/templates/uploader/error.html
<!-- Copyright (C) 2019 Aniol Marti
* This file is part of DAT - UploaderExamensApunts.
*
* DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
-->
{% extends "uploader/header.html" %}
{% block content %}
<h2>{{ error }}</h2>
<h3>{{ error_info }}</h3>
<h4><a href="/">Torna'm al formulari.</a></h4>
{% endblock %}

uploader/templates/uploader/form.html
<!-- Copyright (C) 2019 Aniol Marti
* This file is part of DAT - UploaderExamensApunts.
*
* DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
-->
{% extends "uploader/header.html" %}

{% block scripts %}
{% load static %}
<script type="text/javascript" src="{% static 'uploader/js/document.js' %}" async></script>
<script type="text/javascript" src="{% static 'uploader/js/subject.js' %}" async></script>
<script type="text/javascript" src="{% static 'uploader/js/amaga.js' %}" async></script>
{% endblock %}

{% block content %}
<h1>Puja exàmens i apunts</h1>
    <h4>Si no estàs registrat fes clic <a href="/signup">aquí</a>.</h4>
    <h6>Mida màxima: {{ MAX_FILE_SIZE }} MB</h6>
    <h6>Formats permesos:
    {% for i in content_types %}
        {{ i }}
    {% endfor %}</h6>
<br>
<form method="post" action="/upload/" id="uploader" name="uploader" enctype="multipart/form-data">
    {% csrf_token %}

    <h5>Grau:</h5>
    {{ form.grau }}

    <h5>Assignatura:</h5>
    <div id="assignatura">
        <select name="assig_fake" id="id_assig_fake">
                <option value="---" selected>---</option>
        </select>
    </div>
    {% for d in degrees %}
        <div id="assigG{{ d.id }}">
            <select name="assignatura" id="id_assignatura">
                <option value="---" selected>---</option>
                {% for key, value in subjects.items %}
                    {% if key == d.id %}
                        {% for s in value %}
                            <option value="{{ s.id }}">{{ s.nom }}</option>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            </select>
        </div>
    {% endfor %}

    <h5>Professor:</h5>
    {{ form.professor }}

    <h5>DNI/NIE alumne:</h5>
    {{ form.dni }}

    <h5>Any:</h5>
    {{ form.curs }}

    <h5>Quadrimestre:</h5>
    {{ form.quadrimestre }}

    <h5>Tipus de document:</h5>
    {{ form.document }}

    <div id="exam-{{ exam_id }}">
        <h5>Tipus d'examen:</h5>
        <p></p>
        {{ form.parcial_final }}
        <p></p>
        {{ form.tipus_examen }}
        <p></p>
        Solució: {{ form.solucio }}
    </div>

    <div id="upload">
        <br>
        <h5>Selecciona un fitxer:</h5>
        {{ form.file_upload }}
    </div>

    <br>
    <br>
    {{ form.captcha }}

    <br>
    <br>
    <div>
        <input type="submit" name="submit" value="Enviar" >
        <input type="reset" value="Reiniciar" onClick="amaga();">
    </div>
</form>
{% endblock %}

uploader/templates/uploader/header.html
<!-- Copyright (C) 2019 Aniol Marti
* This file is part of DAT - UploaderExamensApunts.
*
* DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Exàmens i apunts | DAT - UPC</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'uploader/css/style.css' %}" type="text/css" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</head>
<body>
    <div class="container margin-v-big">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

uploader/templates/uploader/success.html
<!-- Copyright (C) 2019 Aniol Marti
* This file is part of DAT - UploaderExamensApunts.
*
* DAT - UploaderExamensApunts is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* DAT - UploaderExamensApunts is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with DAT - UploaderExamensApunts. If not, see <https://www.gnu.org/licenses/>.
-->
{% extends "uploader/header.html" %}
{% block content %}
<h2>El fitxer s'ha pujat correctament.</h2>
<h3><a href="/">Torna'm al formulari.</a></h3>
{% endblock %}